config/routes.rb
Crm::Application.routes.draw do

  # We need to define devise_for just omniauth_callbacks:auth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:session, :password, :registration, :confirmation], path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  scope '(:locale)' do

    # Import paths
    get 'contacts/import_step_1'  => 'contacts#import_step_1'
    post 'contacts/import_step_2' => 'contacts#import_step_2'
    post 'contacts/import_step_3' => 'contacts#import_step_3'    
    get 'tasks/import_step_1'  => 'tasks#import_step_1'
    post 'tasks/import_step_2' => 'tasks#import_step_2'
    post 'tasks/import_step_3' => 'tasks#import_step_3'
    get 'deals/import_step_1'  => 'deals#import_step_1'
    post 'deals/import_step_2' => 'deals#import_step_2'
    post 'deals/import_step_3' => 'deals#import_step_3'
    get 'events/import_step_1'  => 'events#import_step_1'
    post 'events/import_step_2' => 'events#import_step_2'
    post 'events/import_step_3' => 'events#import_step_3'

    mount Ckeditor::Engine => '/ckeditor'
    
    resources :stages, only: [:show]
    
    resources :events do
      post 'add_participant' => 'events#add_participant', as: "add_participant"
      get 'remove_participant/:participant_type/:participant_id' => 'events#remove_participant', as: "remove_participant"
      get 'change_status' => 'events#change_status', as: 'change_status'
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]      
    end
    
    resources :deals do
      post 'add_participant' => 'deals#add_participant', as: 'add_participant'
      get 'remove_participant/:participant_type/:participant_id' => 'deals#remove_participant', as: 'remove_participant'
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end

    resources :tasks, except: [:show]
    
    resources :contacts, only: [:index]
    
    resources :people do
      resources :deals, except: [:index]
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end
    
    resources :companies do
      post 'add_person' => 'companies#add_person', as: "add_person"
      resources :deals, except: [:index]    
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end
  
    resources :authentications, only: [:destroy]
    #match '/auth/:provider/callback' => 'authentications#create'

    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #TODO: fix devise http://stackoverflow.com/questions/24945671/how-to-use-dynamic-scoping-with-devise-and-omniauth
    devise_for :users, skip: :omniauth_callbacks, path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

    resources :users, only: [:edit, :update]
    get '/profile' => 'users#profile', as: 'profile'
    
    namespace :admin do
      resources :users
    end
    
    get '/search/(:search)' => 'search#index', as: 'search'
    
    get 'dashboard/index' => "dashboard#index", as: "dashboard"
  
    get 'options/index', as: 'options'
    get 'options/export', as: 'options_export'

    root :to => 'contacts#index'
  end
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id              :integer          not null, primary key
#  firstname       :string(255)
#  lastname        :string(255)
#  company_id      :integer
#  job             :string(255)
#  description     :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  contact_type_id :integer
#  image           :string(255)
#  full_name       :string(255)
#

class Person < ActiveRecord::Base
  def self.free
    where(company_id: nil)
  end

  belongs_to :company
  has_many :emails, as: :emailable, inverse_of: :emailable, dependent: :destroy
  has_many :phones, as: :phoneable, inverse_of: :phoneable, dependent: :destroy
  has_many :addresses, as: :addressable, inverse_of: :addressable, dependent: :destroy
  has_many :histories, as: :historable
  has_many :tasks, as: :taskable
  has_many :deal_contacts, as: :participatiable
  has_many :deals, through: :deal_contacts
  has_many :event_contacts, as: :participatiable
  has_many :events, through: :event_contacts
  belongs_to :contact_type
  
  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :emails, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true
  accepts_nested_attributes_for :addresses, allow_destroy: true
  
  attr_accessible :company_id, :company_name,
                  :description, :firstname,
                  :job, :lastname, :full_name,
                  :emails_attributes, :phones_attributes,
                  :contact_type_id, :image,
                  :remove_image, :addresses_attributes

  before_validation :set_full_name, on: [ :create, :update ]
  validates_presence_of :full_name
  
  scope :by_name, lambda {|name| where('full_name like ?', name)}

# Attributes to import
  def self.import_columns
    [:firstname, :lastname, :job, :name => :alias]
  end

  # Import rules
  def self.import_rules
    {
      firstname: {required: true},
      lastname: {required: true},
      name: { alias_to: 'company_name' }
    }
  end

  def name
    "#{firstname} #{lastname}"  
  end
  
  def company_name
    company.try(:name)
  end
  
  def company_name=(name)
    self.company = Company.find_or_create_by_name(name) if name.present?
  end
  
  def id_with_class_name
    "#{id}_#{self.class.name}"
  end

  def email
    emails.map(&:email).join('; ')
  end

  def phone
    phones.map(&:phone).join('; ')
  end

  def address
    addresses.map(&:address).join('; ')
  end

  protected
    def set_full_name
      self.lastname = " #{self.lastname}" if (self.firstname.present? && self.lastname.present?)
      self.full_name = self.firstname + self.lastname
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    respond_to do |format|
      if params[:q]
        @people = Person.free.order(:firstname)
          .where("firstname like ? or lastname like ?", "%#{params[:q]}%", "%#{params[:q]}%")
      else
        @people = Person.order(:full_name)
      end
      format.html
      format.json { render json: @people.to_json(methods: :company_name) }
    end
  end
  
  def show
    @person = Person.find(params[:id])
    @history = History.new
    @history.contact = "#{@person.id}_Person"
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end
  
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  def edit
    @person = Person.find(params[:id])
  end  
  
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end  
  
  def update
    @person = Person.find(params[:id])
    
    # Nil company if empty name
    @person.company = nil if params[:person][:company_name] == ''
    
    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end  
  
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.slim
= simple_form_for @person do |f|
  .form-group
    .col-sm-6
      = f.input :firstname, input_html: { class: 'form-control' }
    .col-sm-6
      = f.input :lastname, input_html: { class: 'form-control' }
  .form-group
    .col-sm-4
      = f.input :company_name, input_html: { class: 'form-control' }
    .col-sm-4
      = f.input :job, input_html: { class: 'form-control' }
    .col-sm-4
      = f.association :contact_type, label_method: lambda { |type| t("types.contact.#{type.name}") }, input_html: { class: 'form-control' }
  .form-group
    .col-sm-12
      = f.input :description, class: 'ckeditor', input_html: { toolbar: 'Basic', class: 'form-control' }
  .ibox.float-e-margins
    .ibox-title
    .ibox-content
      h2= t(".general_info")
      h3= t('.email')
      = f.fields_for :emails do |email_form|
        = render 'email_fields', f: email_form
      = link_to_add_fields t('application.email_fields.add_email'), f, :emails
      br
      br

      h3= t('.phone')
      = f.fields_for :phones do |phone_form|
        = render 'phone_fields', f: phone_form
      = link_to_add_fields t('application.phone_fields.add_phone'), f, :phones
      br
      br

      h3= t('.address')
      = f.fields_for :addresses do |address_form|
        = render 'address_fields', f: address_form
      = link_to_add_fields t('application.address_fields.add_address'), f, :addresses
      br
      br

      .hr-line-dashed
      .form-actions
        = f.button :submit, :class => 'btn-primary'
        = link_to t('.cancel', :default => t("helpers.links.cancel")), contacts_path, :class => 'btn'

app/views/people/_person.html.slim
tr
  td.image= image_tag person.image_url(:thumb)
  td
    = link_to person.full_name, person
    - if person.company.present?
      .person_company
        = t(".company")
        = link_to person.company.name, company_path(person.company)
  td.text-right
    = link_to person.emails.first.email, "mailto:#{person.emails.first.email}" if person.emails.present?
    br
    = person.phones.first.phone if person.phones.present?
  td.text-right
    = link_to edit_person_path(person)
      i.fa.fa-edit
    '
    = link_to person_path(person), method: :delete
      i.fa.fa-trash

app/views/people/edit.html.slim
.row.wrapper.page-heading
  .col-xs-12
    h1 = t('.edit_person')
.row.wrapper.white-bg.animated.fadeIn
  .col-xs-12
    .ibox.float-e-margins
      .ibox-title
      .ibox-content
        = render 'form'

app/views/people/new.html.slim
.row.wrapper.page-heading
  .col-xs-12
    h1 = t('.new_person')
.row.wrapper.white-bg.animated.fadeIn
  .col-xs-12
    .ibox.float-e-margins
      .ibox-title
      .ibox-content
        = render 'form'

app/views/people/show.html.slim
ul.breadcrumb
  li
    = link_to t("contacts.index.all_contacts"), contacts_path
    span.divider 
  li
    = "#{@person.firstname} #{@person.lastname}"

h2
  = "#{@person.firstname} #{@person.lastname}"
.buttons-panel
  = link_to t(".edit_person"), edit_person_path(@person), class: "edit"

.row-fluid
  .span8
    h3= t(".general_info")
    table.table-condensed
      tr
        -unless @person.company.nil?
          td= t(".company")
          td= link_to @person.company.name, @person.company
      tr
        td= t(".contact_type")
        td
          - if @person.contact_type.nil?
            = t('.not_set')
          - else
            = t("types.contact.#{@person.contact_type.name}")
      = render @person.emails
      = render @person.phones
      = render @person.addresses
      - unless @person.description.nil?
        tr
          td= t(".description")
          td= @person.description.html_safe

  .span4
    = image_tag @person.image_url
    br
    = render 'upload_image_form', object: @person
    
.tabbable
  = render 'tabs_header'
  .tab-content
    = render 'histories_tab', object: @person
    = render 'tasks_tab', object: @person
    = render 'deals_tab', object: @person