config/routes.rb
Crm::Application.routes.draw do

  # We need to define devise_for just omniauth_callbacks:auth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:session, :password, :registration, :confirmation], path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  scope '(:locale)' do

    # Import paths
    get 'contacts/import_step_1'  => 'contacts#import_step_1'
    post 'contacts/import_step_2' => 'contacts#import_step_2'
    post 'contacts/import_step_3' => 'contacts#import_step_3'    
    get 'tasks/import_step_1'  => 'tasks#import_step_1'
    post 'tasks/import_step_2' => 'tasks#import_step_2'
    post 'tasks/import_step_3' => 'tasks#import_step_3'
    get 'deals/import_step_1'  => 'deals#import_step_1'
    post 'deals/import_step_2' => 'deals#import_step_2'
    post 'deals/import_step_3' => 'deals#import_step_3'
    get 'events/import_step_1'  => 'events#import_step_1'
    post 'events/import_step_2' => 'events#import_step_2'
    post 'events/import_step_3' => 'events#import_step_3'

    mount Ckeditor::Engine => '/ckeditor'
    
    resources :stages, only: [:show]
    
    resources :events do
      post 'add_participant' => 'events#add_participant', as: "add_participant"
      get 'remove_participant/:participant_type/:participant_id' => 'events#remove_participant', as: "remove_participant"
      get 'change_status' => 'events#change_status', as: 'change_status'
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]      
    end
    
    resources :deals do
      post 'add_participant' => 'deals#add_participant', as: 'add_participant'
      get 'remove_participant/:participant_type/:participant_id' => 'deals#remove_participant', as: 'remove_participant'
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end

    resources :tasks, except: [:show]
    
    resources :contacts, only: [:index]
    
    resources :people do
      resources :deals, except: [:index]
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end
    
    resources :companies do
      post 'add_person' => 'companies#add_person', as: "add_person"
      resources :deals, except: [:index]    
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end
  
    resources :authentications, only: [:destroy]
    #match '/auth/:provider/callback' => 'authentications#create'

    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #TODO: fix devise http://stackoverflow.com/questions/24945671/how-to-use-dynamic-scoping-with-devise-and-omniauth
    devise_for :users, skip: :omniauth_callbacks, path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

    resources :users, only: [:edit, :update]
    get '/profile' => 'users#profile', as: 'profile'
    
    namespace :admin do
      resources :users
    end
    
    get '/search/(:search)' => 'search#index', as: 'search'
    
    get 'dashboard/index' => "dashboard#index", as: "dashboard"
  
    get 'options/index', as: 'options'
    get 'options/export', as: 'options_export'

    root :to => 'contacts#index'
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource class: SearchController
  
  def index
    
    # Find companies
    @companies = Company.by_name(params[:search]).order(:name)
    # Remember thier count
    companies_count = @companies.count
    # Remove all but 10 companies to show
    @companies = @companies.limit(10)

    # The same logic for people, tasks, deals and events
    @people = Person.by_name(params[:search]).order(:firstname)
    people_count = @people.count

    # Here we should calculate limit for people
    # because people and companies are displayed in one block 'Contacts'
    if companies_count >= 10
      people_limit = 0
    else
      people_limit = 10 - companies_count
    end
    @people = @people.limit(people_limit)

    # Calculate sum of companies and people
    @contacts_count = companies_count + people_count

    @tasks =  Task.by_name(params[:search]).order("deadline_date desc")
    @tasks_count = @tasks.count
    @tasks = @tasks.limit(10)

    @deals =  Deal.by_name(params[:search]).order(:closing_date)
    @deals_count = @deals.count
    @deals = @deals.limit(10)

    @events = Event.by_name(params[:search]).order(:name)
    @events_count = @events.count
    @events = @events.limit(10)
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_company.html.slim
tr
  td.image= image_tag company.image_url(:thumb)
  td= link_to company.name, company
  td.text-right
    = link_to company.emails.first.email, "mailto:#{company.emails.first.email}" if company.emails.present?
    br
    = company.phones.first.phone if company.phones.present?

app/views/search/_person.html.slim
tr
  td.image= image_tag person.image_url(:thumb)
  td
    = link_to person.name, person
    - if person.company.present?
      .person_company
        = t(".company")
        = link_to person.company.name, company_path(person.company)
  td.text-right
    = link_to person.emails.first.email, "mailto:#{person.emails.first.email}" if person.emails.present?
    br
    = person.phones.first.phone if person.phones.present?

app/views/search/_task.html.slim
tr
  td.type
    = image_tag "types/task/#{task.task_type.name}.png", alt: t("types.task.#{task.task_type.name}")
  td(class="task #{'active' if task.deadline_date > Time.now.to_date}")
    .title
      = task.name
    /.description
    /  = task.description.html_safe
    .date
      = task.deadline_date.to_s
  td.text-right(width='25%')
    - unless task.taskable.nil?
      = link_to task.taskable.name, polymorphic_path(task.taskable)

app/views/search/index.html.slim
.row
  .col-sm-12
    h1= t('.search_results')
- unless @companies.count + @people.count == 0
  .row
    .col-lg-12
      .animated.fadeInUp
        .ibox.contacts
          .ibox-title
            h2= t('.contacts')
          .ibox-content
            table.table.table-condensed.table-striped
              = render partial: 'company', collection: @companies
              = render partial: 'person', collection: @people
            - if @contacts_count > 10
              .more
                = link_to "#{t('.more')} #{(@contacts_count - 10).to_s}", contacts_path(by_name: params[:search])

- unless @tasks.count == 0
  .row
    .col-lg-12
      .animated.fadeInUp
        .ibox.tasks
          .ibox-title
            h2= t('.tasks')
          .ibox-content
            table.table.table-condensed.table-striped
              = render partial: 'task', collection: @tasks
            - if @tasks_count > 10
              .more
                = link_to "#{t('.more')} #{(@tasks_count - 10).to_s}", tasks_path(by_name: params[:search])

- unless @deals.count == 0
  .row
    .col-lg-12
      .animated.fadeInUp
        .ibox.deals
          .ibox-title
            h2= t('.deals')
          .ibox-content
            table.table.table-condensed
              = render @deals
            - if @deals_count > 10
              .more
                = link_to "#{t('.more')} #{(@deals_count - 10).to_s}", deals_path(by_name: params[:search])
  
- unless @events.count == 0
  .row
    .col-lg-12
      .animated.fadeInUp
        .ibox.events
          .ibox-title
            h2= t('.events')
          .ibox-content
            table.table.table-condensed.table-striped
              = render @events
            - if @events_count > 10
              .more
                = link_to "#{t('.more')} #{(@events_count - 10).to_s}", events_path(by_name: params[:search])