config/routes.rb
Crm::Application.routes.draw do

  # We need to define devise_for just omniauth_callbacks:auth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:session, :password, :registration, :confirmation], path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  scope '(:locale)' do

    # Import paths
    get 'contacts/import_step_1'  => 'contacts#import_step_1'
    post 'contacts/import_step_2' => 'contacts#import_step_2'
    post 'contacts/import_step_3' => 'contacts#import_step_3'    
    get 'tasks/import_step_1'  => 'tasks#import_step_1'
    post 'tasks/import_step_2' => 'tasks#import_step_2'
    post 'tasks/import_step_3' => 'tasks#import_step_3'
    get 'deals/import_step_1'  => 'deals#import_step_1'
    post 'deals/import_step_2' => 'deals#import_step_2'
    post 'deals/import_step_3' => 'deals#import_step_3'
    get 'events/import_step_1'  => 'events#import_step_1'
    post 'events/import_step_2' => 'events#import_step_2'
    post 'events/import_step_3' => 'events#import_step_3'

    mount Ckeditor::Engine => '/ckeditor'
    
    resources :stages, only: [:show]
    
    resources :events do
      post 'add_participant' => 'events#add_participant', as: "add_participant"
      get 'remove_participant/:participant_type/:participant_id' => 'events#remove_participant', as: "remove_participant"
      get 'change_status' => 'events#change_status', as: 'change_status'
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]      
    end
    
    resources :deals do
      post 'add_participant' => 'deals#add_participant', as: 'add_participant'
      get 'remove_participant/:participant_type/:participant_id' => 'deals#remove_participant', as: 'remove_participant'
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end

    resources :tasks, except: [:show]
    
    resources :contacts, only: [:index]
    
    resources :people do
      resources :deals, except: [:index]
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end
    
    resources :companies do
      post 'add_person' => 'companies#add_person', as: "add_person"
      resources :deals, except: [:index]    
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end
  
    resources :authentications, only: [:destroy]
    #match '/auth/:provider/callback' => 'authentications#create'

    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #TODO: fix devise http://stackoverflow.com/questions/24945671/how-to-use-dynamic-scoping-with-devise-and-omniauth
    devise_for :users, skip: :omniauth_callbacks, path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

    resources :users, only: [:edit, :update]
    get '/profile' => 'users#profile', as: 'profile'
    
    namespace :admin do
      resources :users
    end
    
    get '/search/(:search)' => 'search#index', as: 'search'
    
    get 'dashboard/index' => "dashboard#index", as: "dashboard"
  
    get 'options/index', as: 'options'
    get 'options/export', as: 'options_export'

    root :to => 'contacts#index'
  end
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  description     :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  contact_type_id :integer
#  image           :string(255)
#

class Company < ActiveRecord::Base
  has_many :people
  has_many :emails, as: :emailable, inverse_of: :emailable, dependent: :destroy
  has_many :phones, as: :phoneable, inverse_of: :phoneable, dependent: :destroy
  has_many :addresses, as: :addressable, inverse_of: :addressable, dependent: :destroy
  has_many :histories, as: :historable
  has_many :tasks, as: :taskable
  has_many :deal_contacts, as: :participatiable
  has_many :deals, through: :deal_contacts
  has_many :event_contacts, as: :participatiable
  has_many :events, through: :event_contacts
  belongs_to :contact_type
  
  mount_uploader :image, ImageUploader
  
  accepts_nested_attributes_for :emails, allow_destroy: true
  accepts_nested_attributes_for :phones, allow_destroy: true  
  accepts_nested_attributes_for :addresses, allow_destroy: true  
  
  attr_accessible :name, :description,
                  :emails_attributes, :phones_attributes,
                  :contact_type_id, :image,
                  :remove_image, :addresses_attributes
  
  validates :name, presence: true,
                   uniqueness: { case_sensitive:  false }
  
  scope :by_name, lambda {|name| where("name like ?", "%#{name}%")}

# Attributes to import
  def self.import_columns
    [:name]
  end

  # Import rules
  def self.import_rules
    {
      name: {required: true}
    }
  end

                  
  def id_with_class_name
    "#{id}_#{self.class.name}"
  end

  def email
    emails.map(&:email).join('; ')
  end

  def phone
    phones.map(&:phone).join('; ')
  end

  def address
    addresses.map(&:address).join('; ')
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  def index
    @companies = Company.order(:name).where("name like ?", "%#{params[:term]}%")
    render json: @companies.map(&:name)
  end
  
  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    @history = History.new
    @history.contact = "#{@company.id}_Company"
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
  
  def add_person
    @company = Company.find(params[:company_id])
    if params[:person_id].present?
      @person = Person.find(params[:person_id])
      @person.update_attributes(company_id: @company.id)
    end
    redirect_to company_url(@company, anchor: "people")
  end
end

app/views/companies/_add_person.html.slim
= form_tag '/people/search', class: "form-search" do
  = text_field_tag :search, params[:search], class: "search-query"
  = submit_tag "Search", name: nil, class: "btn"

app/views/companies/_company.html.slim
tr
  td.image= image_tag company.image_url(:thumb)
  td= link_to company.name, company
  td.text-right
    = link_to company.emails.first.email, "mailto:#{company.emails.first.email}" if company.emails.present?
    br
    = company.phones.first.phone if company.phones.present?
  td.text-right
    = link_to edit_company_path(company)
      i.fa.fa-edit
    '
    = link_to company_path(company), method: :delete
      i.fa.fa-trash

app/views/companies/_form.html.slim
= simple_form_for @company do |f|
  .form-group
    .col-sm-6
      = f.input :name, input_html: { class: 'form-control' }
    .col-sm-6
      = f.association :contact_type, label_method: lambda { |type| t("types.contact.#{type.name}") }, input_html: { class: 'form-control' }

  .form-group
    .col-sm-12
      = f.input :description, class: 'ckeditor', input_html: { toolbar: 'Basic', class: 'form-control' }

  .ibox.float-e-margins
    .ibox-title
    .ibox-content
      h2= t('.general_info')
      p
        | Контактаная информация о компании.
      .form-group
        h3= t('.email')
        = f.fields_for :emails do |email_form|
          = render 'email_fields', f: email_form
        = link_to_add_fields t('application.email_fields.add_email'), f, :emails
        br
        br

        h3= t('.phone')
        = f.fields_for :phones do |phone_form|
          = render 'phone_fields', f: phone_form
        = link_to_add_fields t('application.phone_fields.add_phone'), f, :phones
        br
        br

        h3= t('.address')
        = f.fields_for :addresses do |address_form|
          = render 'address_fields', f: address_form
        = link_to_add_fields t('application.address_fields.add_address'), f, :addresses
        br
        br

  .hr-line-dashed
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), contacts_path, :class => 'btn'

app/views/companies/_tabs_header.html.slim
.tabbable
  ul.nav.nav-tabs
    li.active
      a(href="#histories" data-toggle="tab") = t('.histories')
    li
      a(href="#tasks" data-toggle="tab") = t('.tasks')
    li
      a(href="#people" data-toggle="tab")
        = t('.people')
        = "(#{object.people.count})"
    li
      a(href="#deals" data-toggle="tab") = t('.deals')

app/views/companies/edit.html.slim
.row.wrapper.page-heading
  .col-xs-12
    h1 = t('.edit_company')
.row.wrapper.white-bg.animated.fadeIn
  .col-xs-12
    .ibox.float-e-margins
      .ibox-title
      .ibox-content
        = render 'form'

app/views/companies/index.html.slim
h1 Listing companies

table
  tr
    th Name
    th
    th
    th

  - @companies.each do |company|
    tr
      td= company.name
      td= link_to 'Show', company
      td= link_to 'Edit', edit_company_path(company)
      td= link_to 'Destroy', company, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Company', new_company_path

app/views/companies/new.html.slim
.row.wrapper.page-heading
  .col-xs-12
    h1 = t('.new_company')
.row.wrapper.white-bg.animated.fadeIn
  .col-xs-12
    .ibox.float-e-margins
      .ibox-title
      .ibox-content
        = render 'form'

app/views/companies/show.html.slim
ul.breadcrumb
  li
    = link_to t('contacts.index.all_contacts'), contacts_path
    span.divider 
  li
    = @company.name

h2
  = @company.name
.buttons-panel
  = link_to t('.edit_company'), edit_company_path(@company), class: "edit"

.row-fluid
  .span8
    h3= t('.general_info')
    table.table-condensed
      tr
        td= t('.contact_type')
        td
          - if @company.contact_type.nil?
            = t('.not_set')
          - else
            = t("types.contact.#{@company.contact_type.name}")
      = render @company.emails
      = render @company.phones
      = render @company.addresses
      - unless @company.description.nil?
        tr
          td= t('.description')
          td= @company.description.html_safe
      
  .span4
    = image_tag @company.image_url
    br
    = render 'upload_image_form', object: @company

.tabbable
  = render 'tabs_header', object: @company
  .tab-content
    = render 'histories_tab', object: @company
    = render 'tasks_tab', object: @company
    = render 'people_tab', object: @company
    = render 'deals_tab', object: @company