config/routes.rb
Crm::Application.routes.draw do

  # We need to define devise_for just omniauth_callbacks:auth_callbacks otherwise it does not work with scoped locales
  # see https://github.com/plataformatec/devise/issues/2813
  devise_for :users, skip: [:session, :password, :registration, :confirmation], path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  scope '(:locale)' do

    # Import paths
    get 'contacts/import_step_1'  => 'contacts#import_step_1'
    post 'contacts/import_step_2' => 'contacts#import_step_2'
    post 'contacts/import_step_3' => 'contacts#import_step_3'    
    get 'tasks/import_step_1'  => 'tasks#import_step_1'
    post 'tasks/import_step_2' => 'tasks#import_step_2'
    post 'tasks/import_step_3' => 'tasks#import_step_3'
    get 'deals/import_step_1'  => 'deals#import_step_1'
    post 'deals/import_step_2' => 'deals#import_step_2'
    post 'deals/import_step_3' => 'deals#import_step_3'
    get 'events/import_step_1'  => 'events#import_step_1'
    post 'events/import_step_2' => 'events#import_step_2'
    post 'events/import_step_3' => 'events#import_step_3'

    mount Ckeditor::Engine => '/ckeditor'
    
    resources :stages, only: [:show]
    
    resources :events do
      post 'add_participant' => 'events#add_participant', as: "add_participant"
      get 'remove_participant/:participant_type/:participant_id' => 'events#remove_participant', as: "remove_participant"
      get 'change_status' => 'events#change_status', as: 'change_status'
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]      
    end
    
    resources :deals do
      post 'add_participant' => 'deals#add_participant', as: 'add_participant'
      get 'remove_participant/:participant_type/:participant_id' => 'deals#remove_participant', as: 'remove_participant'
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end

    resources :tasks, except: [:show]
    
    resources :contacts, only: [:index]
    
    resources :people do
      resources :deals, except: [:index]
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end
    
    resources :companies do
      post 'add_person' => 'companies#add_person', as: "add_person"
      resources :deals, except: [:index]    
      resources :tasks, except: [:index, :show]
      resources :histories, only: [:create, :destroy]
    end
  
    resources :authentications, only: [:destroy]
    #match '/auth/:provider/callback' => 'authentications#create'

    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #TODO: fix devise http://stackoverflow.com/questions/24945671/how-to-use-dynamic-scoping-with-devise-and-omniauth
    devise_for :users, skip: :omniauth_callbacks, path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {omniauth_callbacks: 'omniauth_callbacks'}

    resources :users, only: [:edit, :update]
    get '/profile' => 'users#profile', as: 'profile'
    
    namespace :admin do
      resources :users
    end
    
    get '/search/(:search)' => 'search#index', as: 'search'
    
    get 'dashboard/index' => "dashboard#index", as: "dashboard"
  
    get 'options/index', as: 'options'
    get 'options/export', as: 'options_export'

    root :to => 'contacts#index'
  end
end

app/models/deal.rb
# == Schema Information
#
# Table name: deals
#
#  id                  :integer          not null, primary key
#  dealable_id         :integer
#  dealable_type       :string(255)
#  name                :string(255)
#  description         :text
#  currency_id         :integer
#  budget              :decimal(, )
#  budget_type_id      :integer
#  closing_date        :date
#  stage_id            :integer
#  success_probability :integer
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :integer
#

class Deal < ActiveRecord::Base
  attr_accessor :contact
  
  belongs_to :budget_type
  belongs_to :stage
  belongs_to :currency
  belongs_to :user
  belongs_to :dealable, polymorphic: true  
  has_many :deal_contacts
  has_many :people, through: :deal_contacts, source: :participatiable, source_type: 'Person'
  has_many :companies, through: :deal_contacts, source: :participatiable, source_type: 'Company'
  has_many :tasks
  has_many :histories
  
  attr_accessible :budget,              :budget_type_id,
                  :closing_date,        :currency_id,
                  :description,         :name,
                  :user_id,             :stage_id,
                  :success_probability, :contact

  after_initialize :set_success_probability
                  
  before_validation :set_success_probability
  before_validation :set_dealable
                  
  validates :name, :closing_date, :user_id, :stage_id, presence: true
  validates :budget, numericality: { greater_than_or_equal_to: 0 }, allow_blank: true
  validates :success_probability, numericality: { only_integer: true,
                                                  greater_than_or_equal_to: 0,
                                                  less_than_or_equal_to: 100 }
  
  scope :by_name, lambda {|name| where("name like ?", "%#{name}%")}
  
  # Attributes to import
  def self.import_columns
    [:name, :description, :contact, :currency, :budget, :budget_type, :closing_date, :user, :stage, :success_probability]
  end

  # Import rules
  def self.import_rules
    {
      name: {required: true},
      contact: {
        proc: Proc.new { |value| 
            contact = Company.find_by_name(value)
            if contact.nil?
              contact = Person.where('firstname = ? and lastname = ?', value.split[0], value.split[1]).first
            end
            "#{contact.id}_#{contact.class.name}" unless contact.nil?
          }, 
        default: nil
      },
      currency: {
        proc: Proc.new { |value|
          Currency.find_by_name(value) || Currency.find_by_abbreviation(value)
        },
        default: Currency.first
      },
      budget_type: {
        proc: Proc.new { |value|
          budget_type = nil
          BudgetType.all.each do |type|
            if I18n.t("types.budget.#{type.name}") == value
              budget_type = type
              break
            end
          end
          budget_type
        },
        default: BudgetType.first
      },
      closing_date: {required: true},
      user: {
        proc: Proc.new { |value| User.find_by_email(value) }, 
        default: User.current
      },
      stage: {
        proc: Proc.new { |value|
          my_stage = nil
          Stage.all.each do |stage|
            if I18n.t("stages.#{stage.name}") == value
              my_stage = stage
              break
            end
          end
          my_stage
        },
        default: Stage.find_by_success_probability(0)
      }
    }
  end

  def responsible
    User.find(self.user_id)
  end

  def add_participant(participant)
    if participant =~ /_/
      contact_id, contact_type = participant.split('_')
      if contact_type == "Company"
        company = Company.find(contact_id)
        self.companies << company unless self.companies.include?(company)
      else
        person = Person.find(contact_id)
        self.people << person unless self.people.include?(person)
      end
    end
  end  
  
  def remove_participant(participant)
    if participant =~ /_/
      contact_id, contact_type = participant.split('_')
      if contact_type == "Company"
        company = Company.find(contact_id)
        return if self.dealable == company
        self.companies.delete company if self.companies.include?(company)
      else
        person = Person.find(contact_id)
        return if self.dealable == person
        self.people.delete person if self.people.include?(person)
      end
    end    
  end

  def budget_type_name
    self.budget_type.present? ? I18n.t("types.budget.#{self.budget_type.name}") : ''
  end

  def contact_name
    self.dealable.present? ? self.dealable.name : ''
  end

  def currency_name
    currency.name
  end

  def user_email
    user.email
  end

  def stage_name
    I18n.t("stages.#{self.stage.name}")
  end

  def self.to_csv
    columns = [:name, :contact, :description, :currency, :budget, :budget_type, :closing_date, :user, :stage, :success_probability]
    CSV.generate do |csv|
      csv << columns.map { |column| I18n.t("activerecord.attributes.deal.#{column.to_s}")}

      all.each do |deal|
        fields = []
        
        fields << deal.name
        deal.dealable.present? ? fields << deal.dealable.name : fields << ""
        fields << deal.description
        fields << deal.currency.name
        fields << deal.budget || ""
        fields << deal.budget_type_name
        fields << deal.closing_date
        fields << deal.user.email
        fields << I18n.t("stages.#{deal.stage.name}")
        fields << deal.success_probability || ""
        
        csv << fields
      end
    end
  end
  
  private
  
    def set_dealable
      if self.contact =~ /_/
        contact_id, contact_type = self.contact.split('_')
        delete_old_participant(contact_id, contact_type)
        self.add_participant(contact)
        self.dealable_id = contact_id unless contact_id.nil?
        self.dealable_type = contact_type unless contact_type.nil?
      else
        delete_old_participant
        self.dealable = nil
      end
    end
  
    def delete_old_participant(contact_id=nil, contact_type=nil)
      unless self.dealable.nil?
        unless contact_id == self.dealable_id && contact_type == self.dealable_type
          if self.dealable.is_a?(Company)
            self.companies.delete(self.dealable) if self.companies.includes(self.dealable)
          else
            self.people.delete(self.dealable) if self.people.includes(self.dealable)
          end
        end
      end
    end
    
    def set_success_probability
      self.success_probability = 0 if self.success_probability.nil?
      self.success_probability = 0 if self.success_probability < 0
      self.success_probability = 100 if self.success_probability > 100
    end
end

app/controllers/deals_controller.rb
require "#{Rails.root}/lib/importer"

class DealsController < ApplicationController

  include Importer

  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
    @deals = Deal.order(:closing_date)
       
    if params[:by_name].present?
      @deals = @deals.by_name(params[:by_name])
    end

    respond_to do |format|
      format.html
      format.csv { render text: Deal.to_csv }
      format.xls { render html: @deals }
      format.json { render json: @deals.to_json(methods: [:dealable, :responsible, :stage]) }
    end
  end
  
  def show
    @deal = Deal.find(params[:id])
    @history = History.new
    @history.deal = @deal
  end
  
  def new
    @deal = Deal.new
    if params[:company_id].present?
      @deal.dealable = Company.find(params[:company_id])
    end
    if params[:person_id].present?
      @deal.dealable = Person.find(params[:person_id])
    end    
  end
  
  def edit
    @deal = Deal.find(params[:id])
  end
  
  def create
    @deal = Deal.new(params[:deal])
    
    if @deal.save
      redirect_to @deal, notice: 'Deal was successfully created.'
    else
      render "new"
    end  
  end
  
  def update
    @deal = Deal.find(params[:id])

    if @deal.update_attributes(params[:deal])
      redirect_to @deal, notice: 'Deal was successfully updated.'
    else
      render "edit"
    end
  end
  
  def add_participant
    @deal = Deal.find(params[:deal_id])
    @deal.add_participant(params[:participant])
    redirect_to deal_path(@deal, anchor: "participants")
  end
  
  def remove_participant
    @deal = Deal.find(params[:deal_id])
    participant = "#{params[:participant_id]}_#{params[:participant_type]}"
    @deal.remove_participant(participant)
    redirect_to deal_path(@deal, anchor: "participants")
  end
end

app/helpers/deals_helper.rb
# encoding: utf-8
module DealsHelper
  def currency_to_symbol(abbreviation)
    case abbreviation
    when "RUR" then '<span class="rur">p<span>уб.</span></span>'.html_safe
    when "USD" then "$"
    else abbreviation
    end
  end
end

app/views/deals/_badge.html.slim
- if object.stage == Stage.find_by_success_probability(100)
  span.label.label-primary
    = t(".success")
- else
  - if object.closing_date < Time.now.to_date
    span.label.label-danger
      = t(".expired")
    br
    small
      = t(".since")
      '
      = object.closing_date

app/views/deals/_deal.html.slim
tr.deal.hidden-xs
  td
    = render 'deals/badge', object: deal
  td
    .name
      = link_to deal.name, deal
  td(width='20%')
    .contact
      - unless deal.dealable.nil?
        = link_to deal.dealable.name, polymorphic_path(deal.dealable)
      - else
        = t(".client_not_set")

    = deal.responsible.name || deal.responsible.email
  td.text-right(width='20%')
    - if deal.budget.present?
      = number_to_currency(deal.budget, unit: currency_to_symbol(deal.currency.abbreviation))
  td.text-right(width='10%')
    .buttons-panel
      = link_to t(".edit_deal"), edit_deal_path(deal), class: "edit"
tr.deal.visible-xs
  td
    h3.name
      = link_to deal.name, deal
    br
    .contact
      - unless deal.dealable.nil?
        = link_to deal.dealable.name, polymorphic_path(deal.dealable)
      - else
        = t(".client_not_set")
  td.text-right(width='40%')
    - if deal.budget.present?
      = number_to_currency(deal.budget, unit: currency_to_symbol(deal.currency.abbreviation))
    br
    = render 'deals/badge', object: deal
    br
    = deal.responsible.name || deal.responsible.email
    br
    .buttons-panel
      = link_to t(".edit_deal"), edit_deal_path(deal), class: "edit"

app/views/deals/_form.html.slim
= simple_form_for @deal, :html => { :class => 'form-horizontal' } do |f|
  .form-group
    .col-sm-6
      = f.input :name, input_html: { class: 'form-control' }
    .col-sm-6
      - pre = [@deal.dealable].to_json(methods: [:id_with_class_name, :name], only: [])
      = f.input :contact, input_html: { 'data-pre' => pre }
  .form-group
    .col-sm-6
      = f.association :user, label_method: :email, value_method: :id, include_blank: false, input_html: { class: 'form-control' }
    .col-sm-6
      = f.input :closing_date, :wrapper_html => {class: "input-prepend input-append"} do
        = f.input_field :closing_date, as: :string, input_html: { class: 'form-control date_picker' }
  .form-group
    .col-sm-12
      = f.input :description, class: 'ckeditor', input_html: { toolbar: 'Basic' , class: 'form-control' }
  .form-group
    .cal-sm-6
      = f.association :currency, include_blank: false, input_html: { class: 'form-control' }
  .form-group
    .col-sm-6
      = f.input :budget, input_html: { class: 'form-control' }
    .col-sm-6
      = f.association :budget_type, label_method: lambda { |type| t("types.budget.#{type.name}") }, include_blank: false, input_html: { class: 'form-control' }
  .form-group
    .col-sm-6
      = f.association :stage, label_method: lambda { |type| t("stages.#{type.name}") }, include_blank: false, input_html: { class: 'form-control' }
    .col-sm-6
      = f.input :success_probability, input_html: { class: 'form-control' }
  .hr-line-dashed
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), deals_path, :class => 'btn'

app/views/deals/_tabs_header.html.slim
ul.nav.nav-tabs
  li.active
    a(href="#histories" data-toggle="tab") = t(".histories")
  li
    a(href="#tasks" data-toggle="tab") = t(".tasks")
  li
    a(href="#participants" data-toggle="tab")
    a(href="#participants" data-toggle="tab")
      = t(".participants")
      = "(#{object.companies.count + object.people.count})"

app/views/deals/edit.html.slim
.row.wrapper.page-heading
  .col-xs-12
    h1 = t('.edit_deal')
.row.wrapper.white-bg.animated.fadeIn
  .col-xs-12
    .ibox.float-e-margins
      .ibox-title
      .ibox-content
        = render 'form'

app/views/deals/index.html.slim
.row
  .col-sm-12
    h2= t(".deals")
.row
  .col-lg-12
    .animated.fadeInUp
      .ibox.deals
        .ibox-title
          .row
            .col-xs-4
              = render 'filter_form'
            .col-xs-8
              .buttons-panel.pull-right
                = link_to t(".new_deal"), new_deal_path, class: "add"
                = link_to t("import.title"), deals_import_step_1_path, class: "import"
                = link_to t('.export'), deals_path(format: 'xls'), class: "export"
        .ibox-content
          table.table.table-condensed
            = render @deals

app/views/deals/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Сделки">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Название</Data></Cell>
        <Cell><Data ss:Type="String">Контакт</Data></Cell>
        <Cell><Data ss:Type="String">Описание</Data></Cell>
        <Cell><Data ss:Type="String">Валюта</Data></Cell>
        <Cell><Data ss:Type="String">Бюджет</Data></Cell>
        <Cell><Data ss:Type="String">Тип бюджета</Data></Cell>
        <Cell><Data ss:Type="String">Дата закрытия</Data></Cell>
        <Cell><Data ss:Type="String">Ответственное лицо</Data></Cell>
        <Cell><Data ss:Type="String">Стадия</Data></Cell>
        <Cell><Data ss:Type="String">Вероятность успеха</Data></Cell>
      </Row>
      <% @deals.each do |deal| %>
          <Row>
            <Cell><Data ss:Type="String"><%= deal.name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= deal.contact_name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= Sanitize.clean(deal.description) %></Data></Cell>
            <Cell><Data ss:Type="String"><%= deal.currency_name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= deal.budget %></Data></Cell>
            <Cell><Data ss:Type="String"><%= deal.budget_type_name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= deal.closing_date %></Data></Cell>
            <Cell><Data ss:Type="String"><%= deal.user_email %></Data></Cell>
            <Cell><Data ss:Type="String"><%= deal.stage_name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= deal.success_probability %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/deals/new.html.slim
.row.wrapper.page-heading
  .col-xs-12
    h1 = t('.new_deal')
.row.wrapper.white-bg.animated.fadeIn
  .col-xs-12
    .ibox.float-e-margins
      .ibox-title
      .ibox-content
        = render 'form'

app/views/deals/show.html.slim
h2= @deal.name
.buttons-panel
  = link_to t(".edit_deal"), edit_deal_path(@deal), class: "edit"
  
table.table-condensed.deal
  tr
    td= t(".deal_stage")
    td= t(".success_probability")
    td= t(".budget")
    td= t(".closing_date")
  tr
    td= t("stages.# @deal.stage.name ")
    td= @deal.success_probability
    td
      - if @deal.budget.present?
        = number_to_currency(@deal.budget, unit: currency_to_symbol(@deal.currency.abbreviation))
      - else
        = t(".budget_not_set")
    td= @deal.closing_date
    
table.table-condensed
  tr
    td= t(".responsible")
    td= @deal.responsible.email
    
.tabbable
  = render 'tabs_header', object: @deal
  .tab-content
    = render 'histories_tab', object: @deal
    = render 'tasks_tab', object: @deal
    = render 'participants_tab', object: @deal
    